import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/components/navigation/nav";
import { ThemeContextProvider } from "@/context/themeContext";

const font = League_Spartan({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeContextProvider>
        <body
          className={`h-screen lg:w-screen flex flex-col md:flex-row ${font.className}`}
        >
          <Navigation />
          {children}
        </body>
      </ThemeContextProvider>
    </html>
  );
}
